### ISSUE TITLE
UI localization

### ISSUE THREAD

**Issue by artyom-poptsov** [Zemllia/RPGram#5]
The code should be rewritten in such a way that it will allow in the future to add localization and allow the user to change game language.

Currently there are lots of plain messages and commands in Russian in the code.

See also: https://docs.oracle.com/javase/tutorial/i18n/intro/index.html

**Comment by F1uctus** [comment]
I can do this, I've tried to enable 'Resource bundles' in my projects successfully.

**Comment by artyom-poptsov** [comment]
Okay, I assigned you to the task.

**Comment by F1uctus** [comment]
We can use that library for creature names transliteration.
https://github.com/unicode-org/icu
